### ISSUE TITLE
Code review (profiles)

### ISSUE THREAD

**Issue by kahsieh** [cs188-software-design-security-w20/project-5-peas-in-a-pod#16]
Please review and add comments to your own code, then review the following files:

- profile.html
- profile.js
- app.js
- auth.js
- firebase.js

Please fix simple issues directly and comment here (cc the author) for more complex issues.

**Comment by quentintruong** [comment]
we have decided to do code review before profile feature gets finished.
so profile.html and profile.js look fine for now.
talked about app.js auth.js and firebase.js. look fine now
